name: CI/CD

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb qtdeclarative5-dev

      - name: Build and test 'Mytestmenu'
        run: |
          cd testmenu
          qmake testmenu.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestmenu

      - name: Build and test 'Mytestdifficultydialog'
        run: |
          cd testdifficultydialog
          qmake testdifficultydialog.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestdifficultydialog

      - name: Build and test 'Mytesthistory'
        run: |
            cd testhistory
            qmake testhistory.pro 
            make
            xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytesthistory

      - name: Build and test 'Mytestsignupdialog'
        run: |
            cd testsignupdialog
            qmake testsignupdialog.pro
            make
            xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestsignupdialog