name: CI/CD

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb

      - name: Build and test 'Mytestconfirmationdialog'
        run: |
          cd src/tests/testconfirmationdialog
          qmake testconfirmationdialog.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestconfirmationdialog
