name: CI/CD

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb qtdeclarative5-dev

      - name: Build and test 'Mytestmenu'
        run: |
          cd testmenu
          qmake testmenu.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestmenu

      - name: Build and test 'Mytestdifficultydialog'
        run: |
          cd testdifficultydialog
          qmake testdifficultydialog.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestdifficultydialog

      - name: Build and test 'Mytesthistory'
        run: |
            cd testhistory
            qmake testhistory.pro 
            make
            xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytesthistory

      - name: Build and test 'Mytestplayagaindialog'
        run: |
            cd testplayagaindialog
            qmake testplayagaindialog.pro
            make
            xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestplayagaindialog

      - name: Build and test 'Mytesttictactoe'
        run: |
                cd testtictactoe
                qmake testtictactoe.pro
                make
                xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytesttictactoe

      - name: Build and test 'Mytesttictactoe1'
        run: |
                cd testtictactoe1
                qmake testtictactoe1.pro
                make
                xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytesttictactoe1
                
      - name: Build and test 'Mytesttictactoe2'
        run: |
                        cd testtictactoe2
                        qmake testtictactoe2.pro
                        make
                        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytesttictactoe2

      - name: Build and test 'Mytestconfirmationdialog'
        run: |
                        cd testconfirmationdialog
                        qmake testconfirmationdialog.pro
                        make
                        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mytestconfirmationdialog